name: Fetch Job Emails Daily

on:
  schedule:
    # Runs at 21:00 Irish time every day (21:00 Europe/Dublin)
    - cron: '0 20 * * *'  # UTC 20:00 = 21:00 Dublin (BST/IST)
  workflow_dispatch:

jobs:
  fetch-emails:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add this to ensure the workflow has write permissions

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client openai pytz

    - name: Run fetch_emails.py
      env:
        GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
        GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
        GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python fetch_emails.py

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config --global --add safe.directory /github/workspace

    - name: Commit and push CSV changes
      run: |
        git add job_emails.csv
        git commit -m "Update job_emails.csv (auto fetch)" || echo "No changes to commit"
        git push origin main
